# For future me: If rust-analyzer is not working - check `helix --health rust`
# you need to see:
# Binary for language server: /usr/bin/rust-analyzer
[[language]]
name = "rust"

[[language]]
name = "python"
